version: "3.8"

services:
  app:
    build:
      context: .
      args:
        user: ${USER:-laravel}
        uid: ${UID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
      - vendor:/var/www/vendor
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: andalasian
      DB_USERNAME: andalasian
      DB_PASSWORD: T01b01t01
    networks:
      - alrca-net
    restart: unless-stopped

networks:
  alrca-net:
    external: true

volumes:
  vendor: